[[Zenohd]]
arch = "aarch64"
git-tree-sha1 = "a6658750c7ee8a1e6b892b6e5b3ffcfc3eed048d"
os = "macos"

    [[Zenohd.download]]
    sha256 = "347a17f804a763bdd4547f51bc635e061bd074acd993cb7e9a32d49a045fa1eb"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.aarch64-apple-darwin.tar.gz"
[[Zenohd]]
arch = "aarch64"
git-tree-sha1 = "9510d11860e86ae8da740dff5663c7172cf4698a"
libc = "glibc"
os = "linux"

    [[Zenohd.download]]
    sha256 = "b6f031ff77d6421aeb57d4326f4db50fc280ab5fe3a351c2cdc900cf7ead0bfa"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.aarch64-linux-gnu.tar.gz"
[[Zenohd]]
arch = "aarch64"
git-tree-sha1 = "26ae3624233be77cc41fb2a0333f8c207dfa35ba"
libc = "musl"
os = "linux"

    [[Zenohd.download]]
    sha256 = "5f3d9b76896f67c9fa92cc62892c72dee82c1e4436f67b7f83ec385ec0fce077"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.aarch64-linux-musl.tar.gz"
[[Zenohd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4071586074ffe0260909de2c4babcf096f1e838f"
libc = "glibc"
os = "linux"

    [[Zenohd.download]]
    sha256 = "5ec3b8922c52d6d6fef06f8ef19159e15829fa1266115cc972215efe554a60ba"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.armv6l-linux-gnueabihf.tar.gz"
[[Zenohd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2b5c4f34ca708bc0c25f8288a5ad7d334415f467"
libc = "musl"
os = "linux"

    [[Zenohd.download]]
    sha256 = "711202cc317db19960588cb5ec8f7dc275495e01b254bac970ee7ba2bf9394bd"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.armv6l-linux-musleabihf.tar.gz"
[[Zenohd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6976ba9f2f1affe5550e45bac49e3bfb77952802"
libc = "glibc"
os = "linux"

    [[Zenohd.download]]
    sha256 = "eb97d6e7b4d3e3ccff835636787025da388b7569e4018ac6a84dcd62b07b1a06"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.armv7l-linux-gnueabihf.tar.gz"
[[Zenohd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "10b3141957672f5222baf8d2bb7cc11deac276b1"
libc = "musl"
os = "linux"

    [[Zenohd.download]]
    sha256 = "71d60e55e22951469d3542b271a53f526109de7c89e16efb3be4385bf66dc30d"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.armv7l-linux-musleabihf.tar.gz"
[[Zenohd]]
arch = "i686"
git-tree-sha1 = "1f1b9c1f3caef5c75d1f7e63f97ec741e15da39e"
libc = "glibc"
os = "linux"

    [[Zenohd.download]]
    sha256 = "4409aa36f9f9df76575d0db7f63d8a3a9178a17415a04b90c0935c09e741f4ee"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.i686-linux-gnu.tar.gz"
[[Zenohd]]
arch = "i686"
git-tree-sha1 = "27adc9a30c9f47a3534e365e699fc8c5b16e428c"
libc = "musl"
os = "linux"

    [[Zenohd.download]]
    sha256 = "9f38dd8ca12603ecb84c1c6c36ad3937e69a62530cf9ac907a29c80e4025ace6"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.i686-linux-musl.tar.gz"
[[Zenohd]]
arch = "powerpc64le"
git-tree-sha1 = "c1f27479e245c4b01236481963d847108ef9f31a"
libc = "glibc"
os = "linux"

    [[Zenohd.download]]
    sha256 = "4642ee51329d93988b66721158076e68186bd9d3d6b03dd8554e4c2427f7f6f6"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.powerpc64le-linux-gnu.tar.gz"
[[Zenohd]]
arch = "x86_64"
git-tree-sha1 = "08ee4125966c8b7ad24afa95eef598d85bae96b2"
libc = "glibc"
os = "linux"

    [[Zenohd.download]]
    sha256 = "7ea7f3e1f528efb15b793527d0fbb5402de782bcf64c9aa60d95efc6cfebbdfe"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.x86_64-linux-gnu.tar.gz"
[[Zenohd]]
arch = "x86_64"
git-tree-sha1 = "090821b8fb583a203ce8ca54e9d52688f3ceb3f4"
libc = "musl"
os = "linux"

    [[Zenohd.download]]
    sha256 = "1c006694b8fb09d99dafb4bafd59a46a0fa2ba404672e6ac6a39d7aa73d745d3"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.x86_64-linux-musl.tar.gz"
[[Zenohd]]
arch = "x86_64"
git-tree-sha1 = "604dfdbf4da92fd6c8636aa27cc00b794fa881ae"
os = "windows"

    [[Zenohd.download]]
    sha256 = "c9f2c7d11ddb521a224d911e93166503cfe2b233b13cf03bdde0f000151e2135"
    url = "https://github.com/JuliaBinaryWrappers/Zenohd_jll.jl/releases/download/Zenohd-v1.4.0+0/Zenohd.v1.4.0.x86_64-w64-mingw32.tar.gz"
