# Autogenerated wrapper script for Zenohd_jll for x86_64-w64-mingw32
export zenohd

JLLWrappers.@generate_wrapper_header("Zenohd")
JLLWrappers.@declare_executable_product(zenohd)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        zenohd,
        "bin\\zenohd.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
